---
title: "Education_analyses"
author: "Felix Tran"
date: "February 28, 2019"
output: html_document
---

This file contains code for determining how to collapse/recode the education
variable.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(broom)
library(readr)
library(RANN)
```



# Data import
```{r}
county_df <- read_csv('./Cleaned data/County/final_df.csv') %>% 
  select(-c(below_hs_prop, hs_prop, some_college_prop, college_prop))

edu_df <- read_csv('./Raw data/County/ACS 2012-2016 Education.csv') %>% 
  janitor::clean_names() %>% 
  select(county_code = geo_id2,
         below_hs_prop = hc02_est_vc09,
         some_hs_prop = hc02_est_vc10,
         hs_prop = hc02_est_vc11,
         some_college_prop = hc02_est_vc12,
         associates_prop = hc02_est_vc13,
         college_prop = hc02_est_vc14,
         grad_prop = hc02_est_vc15) %>% 
  mutate(county_code = as.integer(county_code),
         below_hs_prop = as.numeric(below_hs_prop),
         some_hs_prop = as.numeric(some_hs_prop),
         hs_prop = as.numeric(hs_prop),
         some_college_prop = as.numeric(some_college_prop),
         associates_prop = as.numeric(associates_prop),
         college_prop = as.numeric(college_prop),
         grad_prop = as.numeric(grad_prop))
edu_df <- edu_df[-1, ]

age_df <- read_csv('./Raw data/County/ACS 2012-2016 Demographics.csv') %>% 
  janitor::clean_names() %>% 
  select(hc03_vc08, hc03_vc09, hc03_vc10, hc03_vc11, hc03_vc12,
         county_code = geo_id2) %>% 
  mutate(young_prop = as.numeric(hc03_vc08) + as.numeric(hc03_vc09) +
           as.numeric(hc03_vc10) + as.numeric(hc03_vc11) +
           as.numeric(hc03_vc12),
         county_code = as.integer(county_code)) %>% 
  select(county_code, young_prop)
age_df <- age_df[-1, ]

county_df <- left_join(county_df, edu_df, by = "county_code") %>% 
  left_join(., age_df, by = "county_code")
```



# Experimented with different categorization of the education variable
```{r}
final_df <- county_df %>% 
  filter(usable == T) %>% 
  mutate(gini = gini * 100) %>%
  mutate(median_income = round(median_income / 10000, digits = 3)) %>% 
  # mutate(urban_rural_code = as.integer((urban_rural_code - 1) / 3)) %>%
  mutate(urban_rural_code = as.factor(urban_rural_code)) %>% 
  mutate(edu_comb = hs_prop + some_college_prop) %>%
  mutate(drop_out = below_hs_prop + some_hs_prop) %>% 
  mutate(higher_edu = associates_prop + college_prop + grad_prop)
```


# OLS regression
```{r}
model_four <- lm(data = final_df, crude_rate ~ gini + 
                   median_age +
                   drop_out + higher_edu +
                   male_prop + 
                   black_prop + native_prop + asian_prop + hispanic_prop + 
                   blue_collar_prop +
                   unemployed_prop +
                   median_income) %>% 
  broom::tidy() %>% 
  mutate(estimate = round(estimate, digits = 2),
         std.error = round(std.error, digits = 2),
         statistic = round(statistic, digits = 2),
         p.value = round(p.value, digits = 2)) %>% 
  mutate(lower_ci = round(estimate - 1.96*std.error, digits = 2),
         upper_ci = round(estimate + 1.96*std.error, digits = 2),
         ci = str_c(lower_ci, upper_ci, sep = ", "))

model_four
```
```{r}
model_four <- lm(data = final_df, crude_rate ~ gini + 
                   young_prop + median_age +
                   below_hs_prop + some_hs_prop + some_college_prop + college_prop +
                   associates_prop + grad_prop +
                   male_prop + 
                   black_prop + native_prop + asian_prop + hispanic_prop + 
                   blue_collar_prop +
                   unemployed_prop +
                   median_income) %>% 
  broom::tidy() %>% 
  mutate(estimate = round(estimate, digits = 2),
         std.error = round(std.error, digits = 2),
         statistic = round(statistic, digits = 2),
         p.value = round(p.value, digits = 2)) %>% 
  mutate(lower_ci = round(estimate - 1.96*std.error, digits = 2),
         upper_ci = round(estimate + 1.96*std.error, digits = 2),
         ci = str_c(lower_ci, upper_ci, sep = ", "))

model_four
```
